version: '3'
services:
  node:
    build: .
    ports:
      - "3000:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

      #https://github.com/bradtraversy/docker-node-mongo/blob/master/index.js